import Head from 'next/head'
import { useState } from 'react'
import Key from './key';

export default function Home() {

  const isNumber = (char) => {
    if (typeof char !== 'string') {
      return false;
    }
    if (char.trim() === '') {
      return false;
    }
    return !isNaN(char);
  }

  const [theme, setTheme] = useState(1);

  const [number, setNumber] = useState("")

  const handleStateChange = (e) => {
    var input = e.target.value
    if(isNumber(input.charAt(input.length - 1)) || input==""){
      var num = input.replace(/,/gi, "");
      var formatNumber= num.split(/(?=(?:\d{3})+$)/).join(",");
      setNumber(formatNumber);
    }
    // console.log("Final Value: ", number)
    // const formatNumber = parseInt(e.target.value).toLocaleString();
  }



  return (
    <div className="h-[100%] max-w-[25rem] py-[100px] mx-auto">
      <Head>
        <title>Calculator App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@100;300;400;700&display=swap" rel="stylesheet" />
      </Head>
      <div className='h-[100%] flex flex-col justify-between align-center gap-[20px]'>
        <div className='flex justify-between'>
          <h4 className='text-[36px] font-[700] text-white'>calc</h4>
          <div className='flex gap-[20px] items-center'>
            <p className='text-[12px] self-end uppercase text-white font-[700] tracking-[2px] mb-[6.5px]'>THEME</p>
            <div className=''>
              <div className='flex justify-between  gap-[10px] text-white text-[12px] px-[5px]'>
                <p>1</p>
                <p>2</p>
                <p>3</p>
              </div>
              <div className='bg-[#232c43] rounded-[999px] h-[23px] flex justify-between items-center px-[4px]'>
                <div className={`${theme===1?"bg-[#d03f2f] ":"bg-[#232c43"} toggleButton`} onClick={()=>(setTheme(1))}></div>
                <div className={`${theme===2?"bg-[#d03f2f] ":"bg-[#232c43"} toggleButton`} onClick={()=>(setTheme(2))}></div>
                <div className={`${theme===3?"bg-[#d03f2f] ":"bg-[#232c43"} toggleButton`} onClick={()=>(setTheme(3))}></div>
              </div>
            </div>
          </div>
        </div>
        <div className='p-[30px] bg-[#182034] rounded-[15px]'>
          <div className='absolute bg-gradient-to-r from-[#182034] w-[50px] h-[48px]'></div>
          <input 
            className='
              outline-0 
              text-[48px] 
              w-[100%] 
              bg-[#182034] 
              text-white 
              font-[700] 
              leading-none 
              m-0 
              p-0
              text-right
            ' 
            onChange={handleStateChange}
            value={number}
          />
        </div>
        <div className='flex-1 grid grid-cols-4 grid-rows-5 gap-[20px] min-h-[300px] bg-[#232c43] p-[30px] rounded-[15px]'>
          <Key value={7} row={1} bg={"#eae3dc"} shadow={"#b4a597"}/>
          <Key value={8} row={1} bg={"#eae3dc"} shadow={"#b4a597"}/>
          <Key value={9} row={1} bg={"#eae3dc"} shadow={"#b4a597"}/>
          <Key value={"DEL"} row={1} bg={"#a2b3e0"} shadow={"#b4a597"}/>
          <Key value={4} row={2} bg={"#eae3dc"} shadow={"#b4a597"}/>
          <Key value={5} row={2} bg={"#eae3dc"} shadow={"#b4a597"}/>
          <Key value={6} row={2} bg={"#eae3dc"} shadow={"#b4a597"}/>
          <Key value={"+"} row={2} bg={"#eae3dc"} shadow={"#b4a597"}/>
          <Key value={1} row={3} bg={"#eae3dc"} shadow={"#b4a597"}/>
          <Key value={2} row={3} bg={"#eae3dc"} shadow={"#b4a597"}/>
          <Key value={3} row={3} bg={"#eae3dc"} shadow={"#b4a597"}/>
          <Key value={"-"} row={3} bg={"#eae3dc"} shadow={"#b4a597"}/>
          <Key value={"."} row={4} bg={"#eae3dc"} shadow={"#b4a597"}/>
          <Key value={"0"} row={4} bg={"#eae3dc"} shadow={"#b4a597"}/>
          <Key value={"/"} row={4} bg={"#eae3dc"} shadow={"#b4a597"}/>
          <Key value={"x"} row={4} bg={"#eae3dc"} shadow={"#b4a597"}/>
          <Key value={"Reset"} row={5} bg={"#a2b3e0"} shadow={"#b4a597"}/>
          <Key value={"="} row={5} bg={"#d03f2f"} shadow={"#b4a597"}/>
        </div>
      </div>
      
    </div>
  )
}
